# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        DB_USER: ${{secrets.DB_USER}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        DB_HOST0: ${{secrets.DB_HOST0}}
        DB_HOST1: ${{secrets.DB_HOST1}}
        DB_HOST2: ${{secrets.DB_HOST2}}
        DB_PORT: ${{secrets.DB_PORT}}
        DB_NAME: ${{secrets.DB_NAME}}
        SENTRY_DNS: ${{secrets.SENTRY_DNS}}
        SENTRY_ID: ${{secrets.SENTRY_ID}}
        AUTH_ADMIN_USERNAME: ${{secrets.AUTH_ADMIN_USERNAME}}
        AUTH_ADMIN_PASSWORD: ${{secrets.AUTH_ADMIN_PASSWORD}}
        AUTH_ADMIN_EMAIL: ${{secrets.AUTH_ADMIN_EMAIL}}
        AUTH_JWT_SECRET: ${{secrets.AUTH_JWT_SECRET}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
